name: Dependency review

on:
  pull_request:
    paths:
      - ".github/dependabot.yml"
      - ".github/workflows/**"
      - "requirements.txt"
      - "requirements.lock"
      - "requirements-build.txt"
      - "requirements-build.lock"
      - "plugins/**"

permissions:
  contents: read

concurrency:
  group: dependency-review-${{ github.ref }}
  cancel-in-progress: true

jobs:
  dependency-review:
    name: Dependency review
    runs-on: ubuntu-24.04
    timeout-minutes: 5
    steps:
      - name: Review dependency changes
        uses: actions/dependency-review-action@a1d282b36b6f3519aa1f3fc636f609c47dddb294 # v5.0.0
        with:
          comment-summary-in-pr: never
          fail-on-severity: high
